# Generated by Django 4.2.5 on 2023-10-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('team_name', models.CharField(max_length=20)),
                ('player_position', models.CharField(max_length=20)),
            ],
        ),
    ]
